name: Java CI             # Name of the workflow

on:                       # When it runs
  push:                   # Triggers on code push
    branches: [ '**' ]    # All branches

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Environment

    steps:
      - uses: actions/checkout@v4       # Pull the code
      - uses: actions/setup-java@v4     # Set up Java
        with:
          distribution: 'zulu'
          java-version: '21'

      - run: ./gradlew test --console=plain --info