name: Java CI             # Name of the workflow

on:                       # When it runs
  push:                   # Triggers on code push
    branches: [ '**' ]    # All branches

jobs:
  build:
    runs-on: ubuntu-latest  # Environment

    steps:
      - uses: actions/checkout@v3       # Pull the code
      - uses: actions/setup-java@v3     # Set up Java
        with:
          distribution: 'zulu'
          java-version: '21'
      - run: ./gradlew build
      - run: ./gradlew test --console=plain --debug --stacktrace --scan
        # Run tests